# Generated by Django 3.2.7 on 2021-09-24 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_subscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='subscriber',
            new_name='user',
        ),
    ]
