# Generated by Django 3.2.7 on 2021-09-24 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0004_rename_user_subscriber_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subscribers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Подписчик'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
